### ISSUE TITLE
Check utente super admin

### ISSUE THREAD

**Issue by pdavide** [AgID/wai-matomo-plugin-SuperUserOnlyRestrictions#2]
Rispetto ai controlli in https://github.com/AgID/wai-matomo-plugin-UsersManagerOnlyAdmin/blob/861182d01e33f4d80acea59b1bf3a4cd903961d9/UsersManagerOnlyAdmin.php#L53-L54
mi sembra di vedere due criticità:

- il controllo verifica che l'utente sia admin (ma in realtà dovrebbe verificare che sia super user), dato che in futuro sarà possibile avere utenti con permessi admin di matomo (vedi https://github.com/AgID/wai-portal/issues/541);
- il controllo `dieIfUsersAdminIsDisabled` fa riferimento al parametro di configurazione [`enable_users_admin`](https://github.com/matomo-org/matomo/blob/f39530ac470024266db514ca8756e694a8c5ec6c/config/global.ini.php#L681) che è correlato alla gestione generica delle utenze e in WAI è impostato, come di default, a 1.

**Comment by axciccu** [comment]
@pdavide Posso agilmente sostituire `checkUserHasSomeAdminAccess` con `checkUserHasSuperUserAccess` ed eliminare il controllo `dieIfUsersAdminIsDisabled` che si rivela inutile.

**Comment by pdavide** [comment]
Closed in #3.
